version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - echo nothing yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - files/*
    - styles/*
    - images/*
